### ISSUE TITLE
Bug: `ansible_playbook` table does not populate `become_user`, `remote_user`, and `gather_facts` columns despite values being present in `playbook.yaml`

### ISSUE THREAD

**Issue by ParthaI** [turbot/steampipe-plugin-ansible#31]
**Describe the bug**
The `ansible_playbook` table is not returning values for the `become_user`, `remote_user`, and `gather_facts` columns, even though the `playbook.yaml` file explicitly contains those fields at the top level of the playbook definition.

**Steampipe version (`steampipe -v`)**
latest

**Plugin version (`steampipe plugin list`)**
steampipe-plugin-ansible v0.3.0

**To reproduce**
1. Create a `playbook.yaml` file with the following content:

```yaml
- name: Ping Ansible Hosts
  hosts: all
  remote_user: ansible
  become: true
  become_user: root
  gather_facts: true

  tasks:
    - name: Ping all hosts
      ping:
      tags:
        - ping
```

2. Run the following query:

```sql
select name, remote_user, become_user, gather_facts from ansible_playbook;
```

3. Observe that the values for `remote_user`, `become_user`, and `gather_facts` are missing or null.

**Expected behavior**
The columns `remote_user`, `become_user`, and `gather_facts` should be populated based on the corresponding fields in the YAML file.

**Additional context**
This issue seems to stem from the plugin's YAML parsing logic possibly ignoring or not mapping these fields correctly from the top-level play definition.
```
